<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profile extends \AppBundle\Entity\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'position', 'name', 'unit_type', 'system', 'frame_width', 'mullion_width', 'sash_frame_width', 'sash_frame_overlap', 'sash_mullion_overlap', 'frame_corners', 'sash_corners', 'threshold_width', 'low_threshold', 'frame_u_value', 'spacer_thermal_bridge_value', 'pricing_scheme', 'pricing_grids', 'pricing_equation_params', 'units', 'supplier_system', 'dictionary_entries', 'fillingTypeProfiles', 'weight_per_length', 'clear_width_deduction'];
        }

        return ['__isInitialized__', 'id', 'position', 'name', 'unit_type', 'system', 'frame_width', 'mullion_width', 'sash_frame_width', 'sash_frame_overlap', 'sash_mullion_overlap', 'frame_corners', 'sash_corners', 'threshold_width', 'low_threshold', 'frame_u_value', 'spacer_thermal_bridge_value', 'pricing_scheme', 'pricing_grids', 'pricing_equation_params', 'units', 'supplier_system', 'dictionary_entries', 'fillingTypeProfiles', 'weight_per_length', 'clear_width_deduction'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Profile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$value]);

        return parent::setId($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$value]);

        return parent::setName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnitType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnitType', []);

        return parent::getUnitType();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnitType($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnitType', [$value]);

        return parent::setUnitType($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSystem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSystem', []);

        return parent::getSystem();
    }

    /**
     * {@inheritDoc}
     */
    public function setSystem($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSystem', [$value]);

        return parent::setSystem($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrameWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrameWidth', []);

        return parent::getFrameWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrameWidth($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrameWidth', [$value]);

        return parent::setFrameWidth($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getMullionWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMullionWidth', []);

        return parent::getMullionWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setMullionWidth($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMullionWidth', [$value]);

        return parent::setMullionWidth($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSashFrameWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSashFrameWidth', []);

        return parent::getSashFrameWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setSashFrameWidth($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSashFrameWidth', [$value]);

        return parent::setSashFrameWidth($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSashFrameOverlap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSashFrameOverlap', []);

        return parent::getSashFrameOverlap();
    }

    /**
     * {@inheritDoc}
     */
    public function setSashFrameOverlap($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSashFrameOverlap', [$value]);

        return parent::setSashFrameOverlap($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSashMullionOverlap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSashMullionOverlap', []);

        return parent::getSashMullionOverlap();
    }

    /**
     * {@inheritDoc}
     */
    public function setSashMullionOverlap($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSashMullionOverlap', [$value]);

        return parent::setSashMullionOverlap($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrameCorners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrameCorners', []);

        return parent::getFrameCorners();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrameCorners($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrameCorners', [$value]);

        return parent::setFrameCorners($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSashCorners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSashCorners', []);

        return parent::getSashCorners();
    }

    /**
     * {@inheritDoc}
     */
    public function setSashCorners($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSashCorners', [$value]);

        return parent::setSashCorners($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getThresholdWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThresholdWidth', []);

        return parent::getThresholdWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setThresholdWidth($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThresholdWidth', [$value]);

        return parent::setThresholdWidth($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getLowThreshold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLowThreshold', []);

        return parent::getLowThreshold();
    }

    /**
     * {@inheritDoc}
     */
    public function setLowThreshold($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLowThreshold', [$value]);

        return parent::setLowThreshold($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrameUValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrameUValue', []);

        return parent::getFrameUValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrameUValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrameUValue', [$value]);

        return parent::setFrameUValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpacerThermalBridgeValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpacerThermalBridgeValue', []);

        return parent::getSpacerThermalBridgeValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpacerThermalBridgeValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpacerThermalBridgeValue', [$value]);

        return parent::setSpacerThermalBridgeValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricingScheme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricingScheme', []);

        return parent::getPricingScheme();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricingScheme($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricingScheme', [$value]);

        return parent::setPricingScheme($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricingGrids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricingGrids', []);

        return parent::getPricingGrids();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricingGrids($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricingGrids', [$value]);

        return parent::setPricingGrids($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricingEquationParams()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricingEquationParams', []);

        return parent::getPricingEquationParams();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricingEquationParams($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricingEquationParams', [$value]);

        return parent::setPricingEquationParams($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addWindow(\AppBundle\Entity\Unit $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWindow', [$value]);

        return parent::addWindow($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWindow(\AppBundle\Entity\Unit $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWindow', [$value]);

        return parent::removeWindow($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setWindows(\Doctrine\Common\Collections\ArrayCollection $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWindows', [$value]);

        return parent::setWindows($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getWindows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWindows', []);

        return parent::getWindows();
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierSystem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierSystem', []);

        return parent::getSupplierSystem();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplierSystem($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplierSystem', [$value]);

        return parent::setSupplierSystem($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeightPerLength($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeightPerLength', [$value]);

        return parent::setWeightPerLength($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeightPerLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeightPerLength', []);

        return parent::getWeightPerLength();
    }

    /**
     * {@inheritDoc}
     */
    public function addUnit(\AppBundle\Entity\Unit $unit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUnit', [$unit]);

        return parent::addUnit($unit);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUnit(\AppBundle\Entity\Unit $unit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUnit', [$unit]);

        return parent::removeUnit($unit);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnits', []);

        return parent::getUnits();
    }

    /**
     * {@inheritDoc}
     */
    public function addDictionaryEntry(\AppBundle\Entity\DictionaryEntry $dictionaryEntry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDictionaryEntry', [$dictionaryEntry]);

        return parent::addDictionaryEntry($dictionaryEntry);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDictionaryEntry(\AppBundle\Entity\DictionaryEntry $dictionaryEntry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDictionaryEntry', [$dictionaryEntry]);

        return parent::removeDictionaryEntry($dictionaryEntry);
    }

    /**
     * {@inheritDoc}
     */
    public function getDictionaryEntries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDictionaryEntries', []);

        return parent::getDictionaryEntries();
    }

    /**
     * {@inheritDoc}
     */
    public function getClearWidthDeduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClearWidthDeduction', []);

        return parent::getClearWidthDeduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setClearWidthDeduction($clear_width_deduction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClearWidthDeduction', [$clear_width_deduction]);

        return parent::setClearWidthDeduction($clear_width_deduction);
    }

}
