<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Project extends \AppBundle\Entity\Project implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }



    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'client_name', 'client_company_name', 'client_phone', 'client_email', 'client_address', 'project_name', 'project_address', 'quote_date', 'quote_revision', 'project_notes', 'shipping_notes', 'lead_time', 'settings', 'frontapp_thread_id', 'frontapp_gdrive_folder_id', 'dapulse_pulse_id', 'extra_id_data', 'units', 'accessories', 'binaryFiles'];
        }

        return ['__isInitialized__', 'id', 'client_name', 'client_company_name', 'client_phone', 'client_email', 'client_address', 'project_name', 'project_address', 'quote_date', 'quote_revision', 'project_notes', 'shipping_notes', 'lead_time', 'settings', 'frontapp_thread_id', 'frontapp_gdrive_folder_id', 'dapulse_pulse_id', 'extra_id_data', 'units', 'accessories', 'binaryFiles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Project $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addBinaryFile(\AppBundle\Entity\BinaryFile $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBinaryFile', [$value]);

        return parent::addBinaryFile($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBinaryFile(\AppBundle\Entity\BinaryFile $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBinaryFile', [$value]);

        return parent::removeBinaryFile($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setBinaryFiles(\Doctrine\Common\Collections\ArrayCollection $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBinaryFiles', [$value]);

        return parent::setBinaryFiles($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getBinaryFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBinaryFiles', []);

        return parent::getBinaryFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientName', []);

        return parent::getClientName();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientName($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientName', [$value]);

        return parent::setClientName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientCompanyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientCompanyName', []);

        return parent::getClientCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientCompanyName($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientCompanyName', [$value]);

        return parent::setClientCompanyName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientPhone', []);

        return parent::getClientPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientPhone($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientPhone', [$value]);

        return parent::setClientPhone($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientEmail', []);

        return parent::getClientEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientEmail($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientEmail', [$value]);

        return parent::setClientEmail($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientAddress', []);

        return parent::getClientAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientAddress($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientAddress', [$value]);

        return parent::setClientAddress($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectName', []);

        return parent::getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectName($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectName', [$value]);

        return parent::setProjectName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectAddress', []);

        return parent::getProjectAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectAddress($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectAddress', [$value]);

        return parent::setProjectAddress($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuoteDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuoteDate', []);

        return parent::getQuoteDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuoteDate($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuoteDate', [$value]);

        return parent::setQuoteDate($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuoteRevision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuoteRevision', []);

        return parent::getQuoteRevision();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuoteRevision($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuoteRevision', [$value]);

        return parent::setQuoteRevision($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingNotes', []);

        return parent::getShippingNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingNotes($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingNotes', [$value]);

        return parent::setShippingNotes($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectNotes', []);

        return parent::getProjectNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectNotes($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectNotes', [$value]);

        return parent::setProjectNotes($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadTime', []);

        return parent::getLeadTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadTime($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadTime', [$value]);

        return parent::setLeadTime($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSettings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettings', []);

        return parent::getSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function setSettings($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSettings', [$value]);

        return parent::setSettings($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrontappThreadId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrontappThreadId', []);

        return parent::getFrontappThreadId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrontappThreadId($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrontappThreadId', [$value]);

        return parent::setFrontappThreadId($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrontappGdriveFolderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrontappGdriveFolderId', []);

        return parent::getFrontappGdriveFolderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrontappGdriveFolderId($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrontappGdriveFolderId', [$value]);

        return parent::setFrontappGdriveFolderId($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDapulsePulseId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDapulsePulseId', []);

        return parent::getDapulsePulseId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDapulsePulseId($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDapulsePulseId', [$value]);

        return parent::setDapulsePulseId($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraIdData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraIdData', []);

        return parent::getExtraIdData();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraIdData($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraIdData', [$value]);

        return parent::setExtraIdData($value);
    }

    /**
     * {@inheritDoc}
     */
    public function addUnit(\AppBundle\Entity\Unit $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUnit', [$value]);

        return parent::addUnit($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUnit(\AppBundle\Entity\Unit $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUnit', [$value]);

        return parent::removeUnit($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setUnits(\Doctrine\Common\Collections\ArrayCollection $value, $setProject = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnits', [$value, $setProject]);

        return parent::setUnits($value, $setProject);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnits', []);

        return parent::getUnits();
    }

    /**
     * {@inheritDoc}
     */
    public function addAccessory(\AppBundle\Entity\Accessory $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAccessory', [$value]);

        return parent::addAccessory($value);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccessory(\AppBundle\Entity\Accessory $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccessory', [$value]);

        return parent::removeAccessory($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessories(\Doctrine\Common\Collections\ArrayCollection $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessories', [$value]);

        return parent::setAccessories($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessories', []);

        return parent::getAccessories();
    }

}
