#regular controllers (from annotations)
app:
    resource: '@AppBundle/Controller/'
    type:     annotation

#rest api controllers
prossimo_app_bundle:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /api #/api - "api" prefix Builded by nginx configuration
    type: rest

pdf_tools_split_n_merge:
    path: /api/pdf/splitmerge
    methods:  [POST]
    defaults: {_controller: AppBundle\Controller\PdfController::splitAndMergeAction}

pdf_tools_extract_table:
    path: /api/pdf/exctracttable
    methods:  [POST]
    defaults: {_controller: AppBundle\Controller\PdfController::extractTableAction}

#rest api documentation
NelmioApiDocBundle:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix:   /doc #/api/doc - "api" prefix Builded by nginx configuration

#fos_user:
#    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

fos_user_security:
    resource: '@FOSUserBundle/Resources/config/routing/security.xml'

fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /profile

fos_user_register:
    resource: '@FOSUserBundle/Resources/config/routing/registration.xml'
    prefix: /register

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting

fos_user_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'
    prefix: /profile

api_login_check:
    path: /api/login_check
